### PR TITLE
Implement support for different source types (CLI untouched for now)

### PR DESCRIPTION
**Pull request by bkabrda**
This is a partial fix for #48. It changes dock's API, but CLI is left untouched for now - I will file a PR for it separately after this is accepted. Note that there are some subtle changes from my proposal in #48, see `docs/apidocs/top.md` diff for documentation.

Also, I believe that we should create a "json-able" class for the whole build configuration (usually called `build_json` in most parts of the source) to be able to validate it right after it enters API functions and to be able to use objects instead of dicts. The way I implemented this PR, the `Source` classes get into play quite a long way down the call chain, which I would like to avoid in the long run.

### CODE REVIEW

**Comment by bkabrda** [comment]
Please don't merge yet, landscape discovered some actual errors that I need to fix first.

**Comment by TomasTomecek** [comment]
will test extensively tomorrow

**Comment by bkabrda** [comment]
Ready for review now!

**Comment by jpopelka** [comment]
The code looks good to me. I haven't tested it manually but the tests look comprehensive and they pass so +1 from me.

**Comment by TomasTomecek** [comment]
Slavek, I have rebased your work against current master, you can find it here https://github.com/DBuildService/dock/tree/107-rebased feel free to pull in my commits, update the PR and let's merge this!

**Comment by TomasTomecek** [comment]
Good job!
Thanks Slavek!
(Merged from command line)

**Comment by bkabrda** [comment]
Thanks!

**Pull request closed without merging**
