### PR TITLE
Store crane registry API in the push configuration.

### PR DESCRIPTION
**Pull request by twaugh**
This ensures it gets stored in the osv3 metadata.

Untested (having trouble testing).

### CODE REVIEW

**Comment by twaugh** [comment]
So, this works in as much as the metadata that gets stored now has e.g.:

```
'repositories': '{"unique": ["mynamespace/myrepo:origin-20150610155943", "https://registry.example.com/mynamespace/myrepo:origin-20150610155943"], "primary": ["docker-hello-world:1.0_1", "docker-hello-world:1.0", "https://registry.example.com/docker-hello-world:1.0_1", "https://registry.example.com/docker-hello-world:1.0"]}'
```

But is that what we need?

**Comment by TomasTomecek** [comment]
I feel like it should be:
```json
{
  "unique": [
    "registry.example.com/mynamespace/myrepo:origin-20150610155943"
  ],
  "primary": [
    "registry.example.com/docker-hello-world:1.0_1",
    "registry.example.com/docker-hello-world:1.0"
  ]
}
```
I guess we need to tune the crane's config and lose the `http[s]://` part.

**Comment by twaugh** [comment]
OK, that might just be my bad local configuration. I was using 'https://...' in the `[registries]` section, when it should just have been the hostname (and maybe port).

But the registry-less parts there e.g. 'docker-hello-world:1.0' come from the docker registries in the push configuration, not the pulp/crane registries.

Perhaps there shouldn't be docker registries set at all, only pulp/crane registries.

**Comment by twaugh** [comment]
OpenShift was setting OUTPUT_REGISTRY= in the environment rather than leaving it unset.

Now I'm getting what you expect.

**Pull request merged**
