### PR TITLE
Get metadata for a container image. (#122)

### LINKED ISSUE #122: Get metadata for a container image
Get following info from the squashed tar.gz:
 - size
 - hash of the file
 - specify used hash `sha256`

and return it similarly as `rpm-packages` after the build.

### PR DESCRIPTION
**Pull request by jpopelka**
Resolves #122

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Neat!

**Comment by TomasTomecek** [comment]
Can you rebase please?

**Comment by jpopelka** [comment]
rebased

**Comment by TomasTomecek** [comment]
:+1:

**Pull request merged**
