### PR TITLE
Avoid traceback when handling dict values that are dicts.

### PR DESCRIPTION
**Pull request by twaugh**
This happens with, for instance, this:

```
"args": {
  "labels": {
    "label1": "value1",
    "label2": "value2"
  }
}
```

The actual traceback looks like this:

```
Traceback (most recent call last):
  File "/usr/bin/dock", line 9, in <module>
    load_entry_point('dock==1.1.1', 'console_scripts', 'dock')()
  File "/usr/lib/python2.7/site-packages/dock-1.1.1-py2.7.egg/dock/cli/main.py", line 187, in run
    cli.run()
  File "/usr/lib/python2.7/site-packages/dock-1.1.1-py2.7.egg/dock/cli/main.py", line 170, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/dock-1.1.1-py2.7.egg/dock/cli/main.py", line 66, in cli_inside_build
    build_inside(input=args.input, input_args=args.input_arg, substitutions=args.substitute)
  File "/usr/lib/python2.7/site-packages/dock-1.1.1-py2.7.egg/dock/inner.py", line 215, in build_inside
    image = dbw.build_docker_image()
  File "/usr/lib/python2.7/site-packages/dock-1.1.1-py2.7.egg/dock/inner.py", line 132, in build_docker_image
    prebuild_runner.run()
  File "/usr/lib/python2.7/site-packages/dock-1.1.1-py2.7.egg/dock/plugin.py", line 203, in run
    plugin_instance = self.create_instance_from_plugin(plugin_class, plugin_conf)
  File "/usr/lib/python2.7/site-packages/dock-1.1.1-py2.7.egg/dock/plugin.py", line 253, in create_instance_from_plugin
    translated_conf = self._translate_special_values(plugin_conf)
  File "/usr/lib/python2.7/site-packages/dock-1.1.1-py2.7.egg/dock/plugin.py", line 248, in _translate_special_values
    if value in translation_dict:
TypeError: unhashable type: 'dict'
```

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Wild idea: how about if we nested into dicts?
Also I think this pr should solve lists since those are mutable too.

**Comment by twaugh** [comment]
Yes, sounds good. Looking at this.

**Comment by twaugh** [comment]
See what you think of this change.

**Comment by TomasTomecek** [comment]
This looks great! Well done!

Small nitpick: could you replace `type() == ...` with `isinstance` please? http://stackoverflow.com/questions/1549801/differences-between-isinstance-and-type-in-python

**Comment by twaugh** [comment]
Good idea. Done.

**Comment by TomasTomecek** [comment]
Excellent!

**Pull request merged**
