### PR TITLE
add manpage

### LINKED ISSUE #40: provide manpage

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #40

TODO:

- [x] package docs & manpage

### CODE REVIEW

**Comment by jpopelka** [comment]
LGTM, though I haven't scanned the ManPageFormatter class thoroughly, it looks like a copy from the pwman3/build_manpage.py

@bkabrda I won't merge this now to not break what you are doing, please merge it the way you like.

**Comment by TomasTomecek** [comment]
I should also update specfile and package the manpage actually.

**Comment by TomasTomecek** [comment]
rebased, packaged docs & manpage; ready for review

**Comment by jpopelka** [comment]
:+1:

**Pull request merged**
