### PR TITLE
Add licence header to source files (#61).

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
You are so going to hate me for this. Could you please use [this license text](https://github.com/DBuildService/osbs/commit/85830fd672cdc6bb0b59cbc4360dad15337aaf3f)? Anyway, if you prefer the longer version and would like to stick with it (which I totally understand), change at least the DBuildService to red hat please.

**Comment by jpopelka** [comment]
no problem, updated

**Comment by TomasTomecek** [comment]
Jirko, you are just too awesome!

**Comment by jpopelka** [comment]
:-D

**Pull request merged**
