### PR TITLE
refactor pushing logic

### LINKED ISSUE #142: refactor pushing to registry
It's a mess now. Let's rewrite it and we get pulp dogfood easily.

### PR DESCRIPTION
**Pull request by TomasTomecek**
so we can consume pulp more easily

This patch removes functionality! "tag by labels" and "tag and push"
plugins lost some arguments:

 * tag and push

   No longer accepts any arguments, it just pushes everything from
   tag_conf to push_conf

 * tag by labels

   No longer accepts any arguments, it just puts images inside tag_conf

Fixes #142

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Test should work now, let me try some builds.

**Comment by TomasTomecek** [comment]
Ready for merge. Review someone, please.

**Comment by twaugh** [comment]
Looks good to me.

**Comment by TomasTomecek** [comment]
Thanks Tim! Feel free to merge.

**Pull request merged**
