### PR TITLE
add dockerfile: snapshot dockerfile

### PR DESCRIPTION
**Pull request by TomasTomecek**
If we edit dockerfile after running "add" plugin, we may expose some
unwanted information.

This patch copies dockerfile when the "add" plugin is run and stores
that snapshot in final image.

CC @jpopelka 
Related #108 

As I think about it, this new behavior should be configurable. What do you think Jirko?

(please don't merge)

### CODE REVIEW

**Comment by jpopelka** [comment]
The code looks good to me.

> this new behavior should be configurable.

You mean conditional ? Like having a switch (bool arg) telling us whether to store the snapshot or final Dockerfile ? That might come in handy, yes.
Or how else configurable ?

**Comment by TomasTomecek** [comment]
> Like having a switch (bool arg) telling us whether to store the snapshot or final Dockerfile ?

Exactly.

**Comment by TomasTomecek** [comment]
rebased & updated; ready to merge from my PoV (not sure how this affects other PRs)

**Comment by TomasTomecek** [comment]
@jpopelka 
you're right! thanks for noticing it

**Pull request merged**
